=== Slicer/ExtensionsIndex/schemas/slicer-extension-catalog-entry-schema-v1.0.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "type": "object",
  "title": "3D Slicer extensions catalog entry schema",
  "description": "Schema for storing information about a 3D Slicer extension to allow it to be listed in the extension catalog.",
  "required": ["$schema", "category", "scmurl"],
  "additionalProperties": true,
  "properties": {
    "@schema": {
      "$id": "#schema",
      "type": "string",
      "title": "Schema",
      "description": "URL of versioned schema."
    },
    "category": {
      "$id": "#category",
      "type": "string",
      "title": "Category used to organize the extension in the extension catalog."
    },
    "scmurl": {
      "$id": "#scmurl",
      "type": "string",
      "title": "Filename or URL of the repository."
    },
    "scmrevision": {
      "$id": "#scmrevision",
      "type": "string",
      "title": "Hash, branch or tag name to identify the revision within the repository."
    },
    "scm": {
      "$id": "#scm",
      "type": "string",
      "title": "Type of revision control system.",
      "enum": ["git", "local"],
      "default": "git"
    },
    "build_dependencies": {
      "$id": "#build_dependencies",
      "type": "array",
      "title": "List of extensions required to build this extension.",
      "additionalItems": false,
      "items": { "type": "string" }
    },
    "build_subdirectory": {
      "$id": "#build_subdirectory",
      "type": "string",
      "title": "Name of the inner build directory in case of superbuild based extension.",
      "default": "."
    },
    "enabled": {
      "$id": "#enabled",
      "type": "boolean",
      "title": "Specify if the extension should be enabled after its installation.",
      "default": true
    }
  }
}

=== Slicer/ExtensionsIndex/DICOMwebBrowser.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Informatics",
  "scmrevision": "main",
  "scmurl": "https://github.com/lassoan/SlicerDICOMwebBrowser"
}

=== Slicer/ExtensionsIndex/SlicerTissueSegmentation.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Segmentation",
  "scmrevision": "main",
  "scmurl": "https://github.com/MarinaSandonis/SlicerTissueSegmentation"
}

=== Slicer/ExtensionsIndex/SlicerCaseIterator.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["SlicerDevelopmentToolbox"],
  "build_subdirectory": ".",
  "category": "Utilities",
  "scmrevision": "master",
  "scmurl": "https://github.com/JoostJM/SlicerCaseIterator.git"
}

=== Slicer/ExtensionsIndex/mpReview.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [
    "SlicerDevelopmentToolbox",
    "QuantitativeReporting",
    "DICOMwebBrowser"
  ],
  "build_subdirectory": ".",
  "category": "Informatics",
  "scmrevision": "master",
  "scmurl": "https://github.com/SlicerProstate/mpReview.git"
}

=== Slicer/ExtensionsIndex/SlicerWMA.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": "inner-build",
  "category": "Libraries",
  "scmrevision": "master",
  "scmurl": "https://github.com/SlicerDMRI/SlicerWMA"
}

=== Slicer/ExtensionsIndex/MeshStatisticsExtension.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["ModelToModelDistance"],
  "build_subdirectory": ".",
  "category": "Shape Analysis",
  "scmrevision": "master",
  "scmurl": "https://github.com/DCBIA-OrthoLab/MeshStatisticsExtension.git"
}

=== Slicer/ExtensionsIndex/RegistrationQA.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["SlicerRT"],
  "build_subdirectory": ".",
  "category": "Registration",
  "scmrevision": "master",
  "scmurl": "https://github.com/gsi-biomotion/Slicer-RegQA.git"
}

=== Slicer/ExtensionsIndex/SegmentationAidedRegistration.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Registration",
  "scmrevision": "e1ce457eb08e69ca49083b8998631bb43f203295",
  "scmurl": "https://github.com/gaoyi/SegmentationAidedRegistration.git"
}
