=== Slicer/ExtensionsIndex/schemas/slicer-extension-catalog-entry-schema-v1.0.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "type": "object",
  "title": "3D Slicer extensions catalog entry schema",
  "description": "Schema for storing information about a 3D Slicer extension to allow it to be listed in the extension catalog.",
  "required": ["$schema", "category", "scmurl"],
  "additionalProperties": true,
  "properties": {
    "@schema": {
      "$id": "#schema",
      "type": "string",
      "title": "Schema",
      "description": "URL of versioned schema."
    },
    "category": {
      "$id": "#category",
      "type": "string",
      "title": "Category used to organize the extension in the extension catalog."
    },
    "scmurl": {
      "$id": "#scmurl",
      "type": "string",
      "title": "Filename or URL of the repository."
    },
    "scmrevision": {
      "$id": "#scmrevision",
      "type": "string",
      "title": "Hash, branch or tag name to identify the revision within the repository."
    },
    "scm": {
      "$id": "#scm",
      "type": "string",
      "title": "Type of revision control system.",
      "enum": ["git", "local"],
      "default": "git"
    },
    "build_dependencies": {
      "$id": "#build_dependencies",
      "type": "array",
      "title": "List of extensions required to build this extension.",
      "additionalItems": false,
      "items": { "type": "string" }
    },
    "build_subdirectory": {
      "$id": "#build_subdirectory",
      "type": "string",
      "title": "Name of the inner build directory in case of superbuild based extension.",
      "default": "."
    },
    "enabled": {
      "$id": "#enabled",
      "type": "boolean",
      "title": "Specify if the extension should be enabled after its installation.",
      "default": true
    }
  }
}

=== Slicer/ExtensionsIndex/ModelClip.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Surface Models",
  "scmrevision": "main",
  "scmurl": "https://github.com/jamesobutler/ModelClip.git"
}

=== Slicer/ExtensionsIndex/slicerPRISMRendering.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Rendering",
  "scmrevision": "master",
  "scmurl": "https://github.com/ETS-vis-interactive/SlicerPRISMRendering"
}

=== Slicer/ExtensionsIndex/TorchIO.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["PyTorch"],
  "build_subdirectory": ".",
  "category": "Utilities",
  "scmrevision": "main",
  "scmurl": "https://github.com/fepegar/SlicerTorchIO.git"
}

=== Slicer/ExtensionsIndex/PathReconstruction.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["MarkupsToModel", "SlicerIGT", "SlicerRT"],
  "build_subdirectory": ".",
  "category": "IGT",
  "scmrevision": "master",
  "scmurl": "https://github.com/SlicerIGT/SlicerPathReconstruction.git"
}

=== Slicer/ExtensionsIndex/ErodeDilateLabel.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Filtering.Morphology",
  "scmrevision": "3f4146ddaa712c8f0a8418f49b2624a1dd6fd20a",
  "scmurl": "https://github.com/tokjun/ErodeDilateLabel.git"
}

=== Slicer/ExtensionsIndex/EasyClip.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Shape Analysis",
  "scmrevision": "master",
  "scmurl": "https://github.com/DCBIA-OrthoLab/EasyClip-Extension.git"
}

=== Slicer/ExtensionsIndex/ResectionPlanner.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "IGT",
  "scmrevision": "master",
  "scmurl": "https://github.com/SlicerIGT/ResectionPlanner.git"
}

=== Slicer/ExtensionsIndex/DebuggingTools.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Developer Tools",
  "scmrevision": "master",
  "scmurl": "https://github.com/SlicerRt/SlicerDebuggingTools.git"
}
