=== Slicer/ExtensionsIndex/schemas/slicer-extension-catalog-entry-schema-v1.0.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "type": "object",
  "title": "3D Slicer extensions catalog entry schema",
  "description": "Schema for storing information about a 3D Slicer extension to allow it to be listed in the extension catalog.",
  "required": ["$schema", "category", "scmurl"],
  "additionalProperties": true,
  "properties": {
    "@schema": {
      "$id": "#schema",
      "type": "string",
      "title": "Schema",
      "description": "URL of versioned schema."
    },
    "category": {
      "$id": "#category",
      "type": "string",
      "title": "Category used to organize the extension in the extension catalog."
    },
    "scmurl": {
      "$id": "#scmurl",
      "type": "string",
      "title": "Filename or URL of the repository."
    },
    "scmrevision": {
      "$id": "#scmrevision",
      "type": "string",
      "title": "Hash, branch or tag name to identify the revision within the repository."
    },
    "scm": {
      "$id": "#scm",
      "type": "string",
      "title": "Type of revision control system.",
      "enum": ["git", "local"],
      "default": "git"
    },
    "build_dependencies": {
      "$id": "#build_dependencies",
      "type": "array",
      "title": "List of extensions required to build this extension.",
      "additionalItems": false,
      "items": { "type": "string" }
    },
    "build_subdirectory": {
      "$id": "#build_subdirectory",
      "type": "string",
      "title": "Name of the inner build directory in case of superbuild based extension.",
      "default": "."
    },
    "enabled": {
      "$id": "#enabled",
      "type": "boolean",
      "title": "Specify if the extension should be enabled after its installation.",
      "default": true
    }
  }
}

=== Slicer/ExtensionsIndex/SlicerHeart.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["SlicerIGT"],
  "build_subdirectory": "inner-build",
  "category": "Cardiac",
  "scmrevision": "master",
  "scmurl": "https://github.com/SlicerHeart/SlicerHeart.git"
}

=== Slicer/ExtensionsIndex/SPHARM-PDM.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["MeshToLabelMap"],
  "build_subdirectory": "SPHARM-PDM-build",
  "category": "SPHARM",
  "scmrevision": "master",
  "scmurl": "https://github.com/NIRALUser/SPHARM-PDM.git"
}

=== Slicer/ExtensionsIndex/T2mapping.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Quantification",
  "scmrevision": "master",
  "scmurl": "https://github.com/gattia/Slicer-T2mapping"
}

=== Slicer/ExtensionsIndex/SkullStripper.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [],
  "build_subdirectory": ".",
  "category": "Segmentation",
  "scmrevision": "master",
  "scmurl": "https://github.com/Slicer/SkullStripper.git"
}

=== Slicer/ExtensionsIndex/RVXLiverSegmentation.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": [
    "MarkupsToModel",
    "SlicerVMTK",
    "SegmentEditorExtraEffects",
    "PyTorch"
  ],
  "build_subdirectory": ".",
  "category": "Segmentation",
  "scmrevision": "main",
  "scmurl": "https://github.com/R-Vessel-X/SlicerRVXLiverSegmentation"
}

=== Slicer/ExtensionsIndex/SegmentRegistration.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["SlicerProstate", "SlicerRT"],
  "build_subdirectory": ".",
  "category": "Registration",
  "scmrevision": "HEAD",
  "scmurl": "https://github.com/SlicerRt/SegmentRegistration.git"
}

=== Slicer/ExtensionsIndex/AblationPlanner.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["ModelToModelDistance"],
  "build_subdirectory": ".",
  "category": "Quantification",
  "scmrevision": "main",
  "scmurl": "https://github.com/naterex23/SlicerAblationPlanner"
}

=== Slicer/ExtensionsIndex/BreastUltrasoundAnalysis.json
{
  "$schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-item-schema-v1.0.0.json#",
  "build_dependencies": ["PyTorch"],
  "build_subdirectory": ".",
  "category": "Utilities",
  "scmrevision": "master",
  "scmurl": "https://github.com/ZhyBrian/SlicerBreastUltrasoundAnalysis.git"
}
